# Generated by Django 4.1.7 on 2023-03-28 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('is_completed', models.BooleanField(default=False)),
                ('due_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
