# Generated by Django 4.1.7 on 2023-05-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='content',
        ),
    ]
