# Generated by Django 4.1.7 on 2023-08-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-updated_at']},
        ),
    ]
